# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/graphs_for_economics',
                'doc_host': 'https://uh2000.github.io',
                'git_url': 'https://github.com/uh2000/graphs_for_economics',
                'lib_path': 'graphs_for_economics'},
  'syms': {'graphs_for_economics.core': {'graphs_for_economics.core.foo': ('core.html#foo', 'graphs_for_economics/core.py')}}}
